### ISSUE TITLE
Great to see what Trump said today. Thanks to all that have been spreading scientific proof of that highly likely wuhan lab leak. 

### ISSUE THREAD

**Issue by EXPOSING-THE-LIKELY-WUHAN-LAB-LEAK** [Project-Evidence/project-evidence.github.io#23]
Great to see what Trump said today. Thanks to all that have been spreading scientific proof of that highly likely wuhan lab leak. That statement today was a victroy for TRUTH so everybody that has been on spreading THE TRUTH about the science of that EXTREMELY LIKELY wuhan lab leak should celebrate today. 

Hopefully his advisors will clarify that the yunnan bats are hundreds of km away from wuhan, but he seemed to notice that slipup and recovered reasonably well at that press conference. 

Still should continue to push on social media (and email news companies) to make sure most of public knows the science involved (especially the possible gain of function enhancements that would look natural) and to slay any attempts at any disinfo smokescreen attempted by some unethical scumbags in bioresearch industry such as peter daszak.

**Comment by Project-Evidence** [comment]
It has been very interesting to watch the evolution of this discussion since we first began tracking the outbreak theories in early January. At first, we figured it was entirely reasonable to discard these conspiracy theories, as it seemed logical that enemies of China would adopt them without factual basis.

But, as we have seen over time, more and more evidence continues to accumulate to support the lab outbreak theory, while the zoonotic event theory appears dead in the water as scientists have failed to find an intermediary animal and China continues to refuse an investigation.

President Trump's comments are positive ones, although not without bias themselves (hence why we did not include them in Revision 2). However, the United States intelligence agencies are the best in the business, and we have full confidence in their ability to uncover the truth.

We admit that we are not the biggest fans of President Trump, however it is very curious that he began calling it the "Chinese Virus" around the same time as these outbreak theories gained prominence in social media. The President lies, but he also has access to the most classified intelligence briefings in the world. So, who knows?

We do believe that we will know the truth by the end of this year. It is positive to see that China is already addressing these concerns with them making Dr. Wenliang a martyr, firing Wuhan officials, and issuing lab safety regulations. However, without that independent investigation, we will always lack the facts to definitively conclude the origins of COVID-19, and that is a statement we believe the entire medical community supports.
