### ISSUE TITLE
Harbin

### ISSUE THREAD

**Issue by angoffinet** [Project-Evidence/project-evidence.github.io#33]
Harbin is a large (11 M+) agglomeration in north-east China, on lockdown since mid april due to re-emergence of Covd19.
Harbin hosts the second chinese P4 laboratory at the Harbin Veterinary Research Institute, a branch of the Chinese Academy of Agronomical Sciences (CAAS). 
In that P4, domestic animals were infected with SARS-CoV-2 in february 2020. They infected 18 ferrets, 20 cats, 5 beagle dogs 5 pigs, 5 chicken, 5 ducks, showing ferrets are highly susceptible, cats moderately so, and other species resistant. Two strains of virus from Wuhan were used.
The work was done in a rush, authorized Jan 22 and 31, paper submitted march 12, and published in Science early april:
https://science.sciencemag.org/content/early/2020/04/07/science.abb7015
That paper has 21 authors and SIX first equal contribution authors, meaning there has been a lot of movement in and out of P4 to perform injections, sampling etc...
The epidemic in Harbin increased when the pandemic subsided in other provinces of China.
The new virus in infected Harbin's patients was sequenced and shows some mutations from the Wuhan strains.
This is interpreted as proof that the virus re-entered China, first from nearby Russia and then from New York, via a student visiting family in Harbin.
Of course, they do not discuss that new sequence compared to the sequence of viruses secreted by infected ferrets in P4 lab.
All this is strong evidence of a second leak from the Harbin P4.
That requires tough (not aggressive) questions and investigation.

**Comment by sanxiyn** [comment]
I agree this requires investigation, but re-introduction from Russia and New York seems totally believable, so I wouldn't call this "strong evidence". Investigation would be helped by publication of sequences, but as far as I can tell they aren't published yet. For that matter, as far as I can tell, no sequences sampled in April in China are published yet. I eagerly wait for their publication.

**Comment by angoffinet** [comment]
I agree that re-entry is not excluded, but either russia or NY, why two places? And I still think that there are so many coincidences. Surely, people came back from USA in many other chinese cities. Why just in Harbin? But I agree we need sequences. My guess it they will never come, but a miracle might happen.

**Comment by sanxiyn** [comment]
No one is accusing South Korea of hiding information, but we also don't have any sequences sampled in April in South Korea. It is not strange we don't have them, at least not yet.

**Comment by wisefish99** [comment]
We have very different understandings of the definition of "strong evidence".

**Comment by angoffinet** [comment]
I agree I should not have used "strong evidence", rather "circumstantial" , but arguing about words will not help much. The situation in Harbin is worrisome. How can we know? How can we end this global madness of virologists doing gain of function experiments which are conceptually quite trivial, still quite dangerous, playing with fire.

**Comment by f-pound** [comment]
@angoffinet Can you provide news articles or other supporting evidence of the lockdown in Harbin   "Harbin is a large (11 M+) agglomeration in north-east China, on lockdown since mid april due to re-emergence of Covd19."

Please also put your findings/URLS in archive.is and archive.org

Thank you

**Comment by sanxiyn** [comment]
This is easy to confirm, for example from Reuters: [Chinese city tightens coronavirus travel curbs in biggest outbreak](https://www.reuters.com/article/us-health-coronavirus-china-harbin/chinese-city-tightens-coronavirus-travel-curbs-in-biggest-outbreak-idUSKCN22409D).

**Comment by f-pound** [comment]
Thanks @sanxiyn, do you have any evidence the 2nd wave was caused by a P4 lab leak in Harbin?

**Comment by wisefish99** [comment]
Non-Chinese media has been overzealous in describing a "lockdown" in Harbin, certainly compared to what lockdowns looked like elsewhere.  

Under the lockdown in Wuhan for instance, many residents were not allowed outside of their apartment communities or even the immediate building they live in, and no vehicles were allowed to leave or enter the city, except for emergency services of course. Travel between districts within the city was also not allowed, the subway was shut down, public buses were parked, etc...

Here's a quote from Kyodo News, which had the same information as the Reuters link shared above by sanxiyn, above, but with extra details about the QR codes. 

https://english.kyodonews.net/news/2020/04/fe41a3ccef67-china-reports-72-new-coronavirus-cases-flare-up-continues-in-north.html

> Harbin, the capital of Heilongjiang Province with a population of some 10 million, has banned all nonresidents and their vehicles from entering residential compounds, according to local authorities.
> 
> In order to go in and out of their guarded residential areas, locals must have a guard scan a QR code on their smartphone, with the color green indicating a COVID-19 risk-free status, while also wearing a mask, the official notice said.

It seems the extent of the Harbin "lockdown" was disallowing people and their cars into apartment communities where they aren't a resident, which was something that was happening pretty much everywhere in the country already for the past few months. For us in Shenzhen, we were only allowed to have non-resident friends come to visit starting at the beginning of April. I use the past tense when referring to the Harbin measures,because as of two days ago, all of Heilongjiang Province has lowered its threat level from "medium" to "low", including Harbin and Suifenhe, so I assume those measures are no longer in effect. 

Source on the threat level returning to "low" is Netease's news posts (Chinese): 
https://3g.163.com/3g/article_cambrian/FC0D9VD00529B4DA.html

In mid-April, Harbin never sealed off entry or exit to the city, or movement around the city. There was debate on Chinese social media about whether it would it would happen or not, and some rumors were flying that the city was going to be "locked down" like Wuhan was. The municipal government had to issue a statement declaring that this was not the case: 

http://hlj.ifeng.com/a/20200416/14109452_0.shtml

> 15日举行的哈尔滨市疫情防控工作第六次新闻发布会上，哈尔滨市对社会上关于“哈尔滨封城，高速公路禁止通行”等不实之言辟谣，希望大家不信谣、不造谣、不传谣，以政府公布的信息为准。                                   
> 
> 同一天，针对网络上有人称“哈尔滨要封城，高速公路禁止通行”，黑龙江省公安厅高速公路交通管理局进行官方辟谣：目前哈市周边所有高速公路，除个别路段因维修扩建的需要采取临时管制措施外均处于正常运行状态。
> 
>  交管部门提醒市民，一切关于高速公路通行的信息，均要以交管部门的正式通告为准，切勿以讹传讹，如果造成不良后果公安机关将追究相关人员的法律责任

My Translation: At the 6th press conference held by the Harbin City Epidemic Prevention and Control Working Team on the 15th, Harbin City said, in regard to the discussion about "Harbin will be locked down, the highway will be closed" etc, that these are false rumors. It is hoped that everyone will not believe rumors, will not create rumors, and will not spread rumors, but treat official announcements as accurate. 

On that same day, with regard to the online discussion about "Harbin will be locked down, the highway will be closed" the highway and transportation management department of Harbin City has confirmed that all Harbin highways are operating as normal, with the exception of those that have been temporarily closed to undergo maintenance.

The transportation management department would like to remind all citizens, that for all information regarding the status of highways and roads, that official announcements from the Department should be treated as accurate. Please don't make errors on top of errors (i.e. spread unsubstantiated rumors). If there are negative effects to public safety, the related persons will be held legally responsible. 

By the way, here's an image of the original post on social media of the "Harbin will be locked down, the highway will be closed" from Weibo. 

https://xw.qq.com/cmsid/20200415A0OB7600


### As far as what Chinese web media has to say about the cases in Harbin in Mid-April: 

There was a spate of local infections in Harbin, including one super-spreader event where one 22-year old student returning to China from the USA (surname Han) infected upwards of 40 people in and around her apartment building, starting with her 87 year old neighbor (ouch...guilt trip). The case numbers stemming back to this one girl eventually reached 80+, and spread across three provinces. 

Here's the link from Tencent News:

https://new.qq.com/omn/20200428/20200428A0Q9OY00.html?pc

I'm too tired to translate the whole thing, but let me know if anything doesn't make sense when you feed it through Google Translate and I'll try to clarify. It's a good summary of the whole Ms. Han super-spreader situation. 

There were also a number of imported cases crossing the border from Russia to Suifenhe, a small city immediately across the border on the Chinese side. I remember last month the Chinese ambassador to Russia was furious about it and took to social media to yell at the overseas Chinese who were returning to China bringing the disease with them, which pissed off Chinese internet users who felt that the motherland should always be willing to welcome its children back, no matter the conditions (obviously they took the plots of recent Chinese blockbusters Operation Red Sea and Wolf Warrior 2 very literally). 

Here's the source on the ambassador to Russia scolding the overseas returnees, complete with video. It also cites some numbers on infected cases coming in from Russia at the time. 

https://supchina.com/2020/04/20/chinas-ambassador-to-russia-scolds-chinese-returnees/

**Comment by angoffinet** [comment]
Lots of papers mentioned Harbin lockdown especially on April 23. For example:https://www.news.com.au/lifestyle/health/health-problems/chinese-city-of-harbin-goes-into-lockdown-as-new-coronavirus-clusters-emerge/news-story/dfe6b292820844f7553525806e49e59a
Then, there are videos of empty streets, and rumors about the "new" virus there being more aggressive. But this is unverifiable.
If we stick to facts:
1. While epidemic was damped in Wuhan and other places, Harbin was special and required measures because of new outbreaks.
2. Official explanation was initially that SARS-CoV2 re-entered from Siberia (which is about 200 km from Harbin).
3. Another official explanation was that a student came from New York to visit. After being quarantined and tested negative, she went out and was after all positive and infected friends etc... She is mentioned by firstname only. Unverifiable.
4. Veterinary Institute in Harbin has a P4 biolab. They received authorization to work on cov2 in january 22 and 31. They infected ferrets (18), cats (20), dogs (5), pigs (5), chicken (5) and ducks (5) and submitted a paper to Science on march 12. That paper was publihed beginning april:
https://science.sciencemag.org/content/early/2020/04/07/science.abb7015
That paper has 21 authors and SIX CO-FIRST authors. That means that those 6 young scientists (PhD students or postdocs probably) went in and out of the P4 often in february. An accidental leak in those circumstances is definitely likely.
5. That Science study used two strains of CoV2 from Wuhan. Virus sequenced from recent outbreak in Wuhan is slightly different according to Global China (which is not prowestern...):
http://www.globaltimes.cn/content/1187066.shtml
This is presented to indicate re-entry of Cov2 via the student ("Han").
However, passing Cov2 is ferrets & cats (both susceptible) could also generated variants, slight mutations.
Therefore, I am not claiming to prove that recent outbreaks in Harbin are due to leaks. 
I claim only this is is PLAUSIBLE and should be INVESTIGATED. 
This can be done by:
1.  Sequencing virus not only in Harbin patients, but also in animals infested in the P4 lab.
2. Inspecting lab reports and check whether lab employees have had covid19 and what virus then?
3. Interview lab personnel and see if some got covid19, when, and infected contacts, etc...
Unfortunately, chinese authorities refuse all cooperation on this, resulting in uncontrolled rumors.

**Comment by angoffinet** [comment]
Sorry Franck. I am a neurobiologist and 69 years old, not familiar with
GitHub (to say the least). Unable to use this well. Sorry again.
Andre GOFFINET, MD, PhD
Prof. em. Institute of Neuroscience
University of Louvain, Belgium
+32 (0) 473 899818

**Comment by wisefish99** [comment]
1. There is no lockdown in Harbin currently, and there was no lockdown in Harbin before. This is supported by both Chinese and Western media reports, which call the measures a "lockdown" but **describe** something that is a not a lockdown at all, i.e. restrictions on non-residents entering apartment complexes. Freedom of movement around or in/out of the city was and is NOT restricted. We're talking about a city of 11 million + people. If the city was locked down, we would know it.  It would be all over social media and there would be tons of articles about it. 

2. Empty streets is what you'd see in any major city where the citizens are scared to go outside because there's been a surge of cases. 

3. Suifenhe is a small city with limited medical resources. I come from a small town in the United States. It has a small medical clinic with limited equipment and resources. If I wanted treatment for a serious illness, I would travel to the closest large city. Harbin is the capital of Heilongjiang. 

You state that the official explanation is unverifiable, with no proof at all, in favor of a lab release theory that has no evidence, and that would require a huge cover-up. Occam's Razor applies to most things, most of the time. Imported cases from Russia and the United States is a far simpler and more reasonable explanation than a cover-up involving a vet lab in Harbin. 

Based on a full cataloging of the super-spreader event, Chinese netizens were even able to create a full "infection family tree" of how Ms. Han infected her neighbor which subsequently led to 40+ more people getting infected. Their surnames, ages, and relationship to each other are all included, and this has been shared around online (actually, some of the more nervous netizens used it as evidence for why they should Harbin SHOULD go into lockdown). 

Is this all an elaborate coverup? How many people are involved in this coverup? Were these infected cases fabricated, or are they also part of the coverup? Does Ms. Han exist or not? Does she have a family and friends who are all being silenced? What does Harbin government gain by announcing false cases with a false origin story, names, and ages?  If the Suifenhe cases trace back to the Harbin lab 200 miles away, how did the infection spread from the provincial capital to a small town on the border with Siberia? If there was a cover-up to conceal the truth about where the cases came from, **why wouldn't they just hide the evidence of the cases entirely**?

You're saying "Yes it could be A, and A makes sense and the evidence points to A, but it could also be Z, although Z would be illogical, unreasonable and more difficult." There is no basis for Z to be "definitely likely" or "PLAUSIBLE". 

This is unscientific. I believe your fondness for your theory of potential Harbin lab release and overemphasis on coincidence is clouding your judgment. 

**Also**: No country, not the USA, not Belgium, not China, is under any OBLIGATION to let researchers from a foreign country enter their borders, conduct forensic investigations, dig around in labs, and try to find evidence that confirms or denies rumors. They are also under no obligation to conduct an investigation to the standards or using the methods that anyone else think is appropriate or necessary. You're within your rights to suggest it, and they're within their rights to tell you to go to hell, and that's that.

**Comment by angoffinet** [comment]
OK,I don't discuss this any loner with you, because you are clearly biased
against any investigation.
An investigation is not interference with internal affairs when the whole
planet is concerned.
That should be evident to anybody, except you and the chinese communist
party.
And I stop here.
Take care,
Andre GOFFINET, MD, PhD
Prof. em. Institute of Neuroscience
University of Louvain, Belgium
+32 (0) 473 899818
