### ISSUE TITLE
Consider Francis Boyle's views for section "A Note on Biowarfare"

### ISSUE THREAD

**Issue by sbellem** [Project-Evidence/project-evidence.github.io#5]
Thank you very much for your work.

---

[Francis Boyle](https://law.illinois.edu/faculty-research/faculty-profiles/francis-boyle/) is a professor of international law at the University of Illinois College of Law.

> He has advised numerous international bodies in the areas of human rights, war crimes and genocide, nuclear policy, and **bio-warfare**.

> He drafted the U.S. domestic implementing legislation for the **Biological Weapons Convention**, known as the [**Biological Weapons Anti-Terrorism Act of 1989**](https://en.wikipedia.org/wiki/Biological_Weapons_Anti-Terrorism_Act_of_1989), that was approved unanimously by both Houses of the U.S. Congress and signed into law by President George H.W. Bush.

Now, for multiple years he's been ignored by mainstream media, and only appears on alternative media. Some people may discredit him right away because they may not like the channels where he appears, but I feel his views deserve to be heard and debated at the very least.

He has appeared on Alex Jones multiple times, and is very vocal and clear about the type of work that is being done in BSL-4 laboratories. Now, I am not qualified to comment on the accuracy of his claims. However in the section "[A Note on Biowarfare](https://project-evidence.github.io/#%28part._biowarfare%29)" you cite the Biological Weapons Convention, preceding it with the argument:

> Furthermore, even if these labs are engaging in "bio-warfare" research, depending on the type of research, it would still be permissible under international law

I find this extremely problematic given that the very person who drafted the treaty you cite disagrees very sharply according to recent interviews he has given.

It seems to me that this topic is most probably a legal matter, and an interpretation of that treaty, but then you should present the views of various people and I really do not see why Francis Boyle's view would not be considered.

For instance, from an [interview with Sherwood Ross](https://www.naturalnews.com/2020-02-24-prof-francis-boyle-13000-death-scientists-hard-at-work-destroying-humanity.html):

> **The American legal authority who in 1989 drafted the law Congress enacted to comply with the 1972 Biological Weapons Convention says the U.S. today [October 11, 2015] is in flagrant violation of that Convention.**
>
> “Since Sept. 11, 2001, we have spent somewhere in the area of $100 billion” on offensive biological warfare, charges Professor Francis Boyle of the University of Illinois, Champaign.
>
> Boyle said an estimated 13,000 “death scientists” in 400 laboratories in the U.S. and abroad, are employed making new strains of offensive killer germs that will be resistant to vaccines.

I don't see how this can be left out, unless the entire discussion on bio-warfare is totally removed.

It may also be relevant to cite [The Biological Weapons Convention protocol should be revisited](https://thebulletin.org/2019/11/the-biological-weapons-convention-protocol-should-be-revisited/) from the Bulletin of Atomic Scientists.

### Pull Request worthy?
If this is worthy of a pull request I can make one.

### Disclaimer
I do not have any substantial relevant knowledge. I just wish to help, as someone who lives on a planet that may be under a great danger that may be underestimated.

**Comment by Project-Evidence** [comment]
In regards to Francis Boyle, we will respond with [this comment](https://github.com/Project-Evidence/project-evidence.github.io/issues/8#issuecomment-623008453).

In regards to the BWC, it is a tough subject. It is very likely that every signatory country to the BWC is in violation of it and has been since it was signed. As you stated, it is up to legal interpretation.

Once particular point we'd like to address is this statement:
> The American legal authority who in 1989 drafted the law Congress enacted to comply with the 1972 Biological Weapons Convention says the U.S. today [October 11, 2015] is in flagrant violation of that Convention.

We do not believe there is any evidence to suggest that Professor Boyle has insights into the inner workings of the U.S. bioweapons program, since his last interaction with it was in 1989. It is entirely possible and maybe likely that he possesses evidence the public does not, however, until such evidence is made public including these statements conflicts with our Sourcing Policy.

Feel free to make a PR to amend our section on the BWC if you think it needs work. We will take a look as long as it follows the Sourcing Policy. Unfortunately this disqualifies "alternative" media such as InfoWars or Zerohedge, but this was a conscious decision made to ensure the accuracy of our own claims as we know that many people would discard the entire document if we sourced alternative media. However, if you can find a Francis Boyle interview on mainstream media, we would happily accept it.
